// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edkhwawqwtvuydgwzvrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVka2h3YXdxd3R2dXlkZ3d6dnJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTEzMzIsImV4cCI6MjA3MDY2NzMzMn0.-a6ptLOO6Tl6B6BvVj3vdCt7RwTkdv8rpROxgp-o5M0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});